### ISSUE TITLE
Swiping with 3 fingers

### ISSUE THREAD

**Issue by iluuu1994** [Kapeli/SwipableWebView#1]
I have the swiping enabled for three fingers,
System <strong>Preferences > Trackpad > More Gestures > Swipe Between pages</strong>

therefore, it won't work with either two or three fingers...

**Comment by Kapeli** [comment]
That's what it's supposed to do. Three finger swipe support is trivial to add (swipeWithEvent:), and is outside the scope of this. This is for two fingers (on a trackpad) or one finger (on a Magic Mouse).

**Comment by iluuu1994** [comment]
I'm only changing the amount of fingers, the function should stay the same, in my opinion.
All other apps support this, but without an animation.

If you don't agree you can close the issue.

Thanks anyway, cool project

**Comment by Kapeli** [comment]
This is just a implementation for two-finger swipes.

Three-finger swipes are different mostly because there is no graphical indication. Look up swipeWithEvent: for more info on how to implement it. Two-finger swipes take over scrolling, and hence need a graphical indication, while three-finger swipes do not.

For what it's worth, I personally hate two-finger swipes and I use three-finger swipes too. However, supporting three-finger swipes is really really easy and it's a whole different thing from supporting two-finger swipes, and there's no need to bloat this code with it.
